#!/usr/bin/env bash

set -o errexit
set -o pipefail
set -o nounset

dir=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )

if [ -t 0 ]; then
    # URLs are passed as an argument value
    if (( $# != 1 )) ; then
        echo "Usage: blacklight-query urls.txt"
        echo "Usage: cat urls.txt | blacklight-query"
        echo
        echo "Please provide a list of URLs, where each URL is on its own line."
        exit 1
    fi
    "$dir/node_modules/.bin/ts-node" --project "$dir/tsconfig.json" "$dir/src/main.ts" $1
else
    # URLs are piped to stdin (and saved to urls.txt)
    echo > urls.txt
    while read -r line ; do
        echo $line >> urls.txt
    done
    "$dir/node_modules/.bin/ts-node" --project "$dir/tsconfig.json" "$dir/src/main.ts" urls.txt
fi
